insert into hero(name,id) values('Ms Nice',1);
insert into hero(name,id) values('Yes Man',2);
insert into hero(name,id) values('Bombastico',3);
insert into hero(name,id) values('Fennel',4);
insert into hero(name,id) values('Magnostic',5);
insert into hero(name,id) values('Duck Man',6);
insert into hero(name,id) values('Silly Putty Man',7);
insert into hero(name,id) values('Company Man',8);
-- insert into heroDetails(peso,altura,descripcion) values (86,1.86,'Heroe modelo');
-- insert into heroDetails(peso,altura,descripcion) values (46,1.56,'Buen heroe');
-- insert into heroDetails(peso,altura,descripcion) values (40,1.10,'Buen heroe');
-- insert into heroDetails(peso,altura,descripcion) values (87,1.98,'Buen heroe');
-- insert into heroDetails(peso,altura,descripcion) values (88,1.34,'Mal heroe');
-- insert into heroDetails(peso,altura,descripcion) values (82,1.60,'Heroe modelo');
-- insert into heroDetails(peso,altura,descripcion) values (90,1.89,'Heroe modelo');
-- insert into heroDetails(peso,altura,descripcion) values (56,1.66,'Heroe modelo');
-- insert into heroDireccion(direccion) values ('Avenida Heroica 724');
-- insert into heroDireccion(direccion) values ('Avenida Heroica 700');
-- insert into heroDireccion(direccion) values ('Avenida Heroica 562');
-- insert into heroDireccion(direccion) values ('Avenida Heroica 958');
-- insert into heroDireccion(direccion) values ('Avenida Heroica 102');
-- insert into heroDireccion(direccion) values ('Avenida Heroica 1');
-- insert into heroDireccion(direccion) values ('Avenida Heroica 204');