create table IF NOT EXISTS heroDetails(peso INT  , altura INT  ,descripcion VARCHAR(50)  , id INT );
create table IF NOT EXISTS heroDireccion(direccion VARCHAR(50)  , id INT  );
create table IF NOT EXISTS hero(name VARCHAR(50)  ,direccionId INT  , detalleId INT  , id INT  );
insert into heroDetails(peso,altura,descripcion,id) values (86,1.86,'Heroe modelo',88);
insert into heroDetails(peso,altura,descripcion,id) values (46,1.56,'Buen heroe',77);
insert into heroDetails(peso,altura,descripcion,id) values (40,1.10,'Buen heroe',66);
insert into heroDetails(peso,altura,descripcion,id) values (87,1.98,'Buen heroe',55);
insert into heroDetails(peso,altura,descripcion,id) values (88,1.34,'Mal heroe',44);
insert into heroDetails(peso,altura,descripcion,id) values (82,1.60,'Heroe modelo',33);
insert into heroDetails(peso,altura,descripcion,id) values (90,1.89,'Heroe modelo',22);
insert into heroDetails(peso,altura,descripcion,id) values (56,1.66,'Heroe modelo',11);
insert into heroDireccion(direccion,id) values ('Avenida Heroica 724',88);
insert into heroDireccion(direccion,id) values ('Avenida Heroica 700',77);
insert into heroDireccion(direccion,id) values ('Avenida Heroica 562',66);
insert into heroDireccion(direccion,id) values ('Avenida Heroica 958',55);
insert into heroDireccion(direccion,id) values ('Avenida Heroica 102',44);
insert into heroDireccion(direccion,id) values ('Avenida Heroica 1',33);
insert into heroDireccion(direccion,id) values ('Avenida Heroica 204',22);
insert into heroDireccion(direccion,id) values ('Avenida Marcos 201',11);
insert into hero(name,direccion,detalle,id) values('Ms Nice',11,11,11);
insert into hero(name,direccion,detalle,id) values('Yes Man',22,22,22);
insert into hero(name,direccion,detalle,id) values('Bombastico',33,33,33);
insert into hero(name,direccion,detalle,id) values('Fennel',44,44,44);
insert into hero(name,direccion,detalle,id) values('Magnostic',55,55,55);
insert into hero(name,direccion,detalle,id) values('Duck Man',66,66,66);
insert into hero(name,direccion,detalle,id) values('Silly Putty Man',77,77,77);
insert into hero(name,direccion,detalle,id) values('Company Man',88,88,88);
